### ISSUE TITLE
Collaboration with external actors to validate/process the command 

### ISSUE THREAD

**Issue by pawelkaczor** [strongtyped/fun-cqrs#39]
Is modelling of such collaboration possible using fun-cqrs?

**Comment by rcavalcanti** [comment]
Yes, it is. 
The  handling of commands can be done async. It can be a service call or a message sent to an actor.

For that you have to define a asyncHandler instead of a simple handler.

An asyncHandler receives a function from Command => Future[Event].
Or, asyncHandler.manyEvents which receives a function from Command => Future[List[Event]]

That way you ask another actor to do some validation and is the answer is positive, map the it to the events you need to produce.

**Comment by pawelkaczor** [comment]
Thanks for the answer. Now I see how it works. Good job! 

Would be interesting to compare your impl of AR with the one from Denis Mikhaylov: https://github.com/notxcain/akka-ddd/blob/master/akka-ddd-core/src/main/scala/pl/newicom/dddd/aggregate/AggregateRootActor.scala

**Comment by rcavalcanti** [comment]
Interesting. I need to make some time to look into it. 

Our main design goal was to have the aggregate behavior and protocol (commands and events) coded outside akka. Which seems to be his (or your, I see is a fork from a project of yours) approach as well. 

Thanks for the link.

**Comment by pawelkaczor** [comment]
I just realized that the `tell` pattern can not be used for the collaboration (with the AggregateActor as the participant / sender).

**Comment by rcavalcanti** [comment]
Indeed, the goal is to use `ask` from inside a `handleCommandAsync`
