### ISSUE TITLE
Example application. Ensuring Globally unique names for each Lottery Game

### ISSUE THREAD

**Issue by CrowdHailer** [strongtyped/fun-cqrs#46]
First thanks very much for Fun.CQRS.
I am building my first CQRS based system and am using this Library. It would be great if there was a place to discuss it. I have questions that might not want to be issues. For example I am curious in the Lottery example if you had a requirement that each Game had a unique name how you would add this in?

If you have no plans can I suggest [Gitter](http://gitter.im/).

**Comment by rcavalcanti** [comment]
Hi Peter, 

We do have a Gitter channel. 
https://gitter.im/strongtyped/fun-cqrs?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge

You can also ask question here and start a discussion that become a feature request.

**Comment by rcavalcanti** [comment]
I marked this issues as a 'question'. We can discuss it here and eventually make it 'enhancement'

**Comment by CrowdHailer** [comment]
I'm sorry I don't know how I missed that gitter link in the README. right where I would expect as well.

**Comment by CrowdHailer** [comment]
So my question is; How to go about adding the requirement that each lottery game has a unique name. So that they can be looked up by that name. I have had some thoughts about how to achieve this(below). but guess that someone else must have had a similar requirement.

- Option 1, Have the code that initially creates the Game Actors check if a name is taken and if not tell the Actor its name and the name  becomes a property on the Game actor as it is currently implemented. Not sure how changing a name would work.
- Option 2, Have a game actor ask a new actor type(call it games listing) if a name is available each time it needs to change its name. I think this could cause race conditions, when a game asks the listing if a name is available and the listing actor return yes. The game starts the process of changing its name but crashes before the name is committed. The listing will record that someone took the name but the game process will not have recorded that it got a new name.

**Comment by rcavalcanti** [comment]
In both cases there is the possibility of creation an inconsistent state. 

Option 1 is the best one because it doesn't not require the creation of a new actor. Although Fun.CQRS is strongly inspired by Akka, the intent is to stay Akka agnostic and Option 2 would invalidate this intention. 

This can be achieved by defining a support table on the write side to control the uniqueness of the name. Note that this is not a read side table or view. Its sole purpose is to support the invariants on the write side.

Than the creation of Lottery would be coded like:
```scala
object LotteryCreationService {
   def reserve(id: LotteryId, name: String): Future[Unit] = {
     // here some logic to check if the name is already in use or not
     // if not in use, add it to table and return Future.success 
     // if in use, Future.failure
   }
}
def createLottery(lotteryId: LotteryId) = 
    actions[Lottery]
      .handleCommandAsync {
        cmd: CreateLottery => LotteryNameReservationService.reserve(lotteryId, cmd.name).map { _ =>
           LotteryCreated(cmd.name, metadata(lotteryId, cmd))
       }
      }
      .handleEvent {
        evt: LotteryCreated => Lottery(name = evt.name, id = lotteryId)
      }
```

However, we can still have the situation where the reservation succeeds, but the system shutdowns or crashes just before `LotteryCreated` event is persisted. The name is reserved, but the Lottery is not created. 

The only way to solve that is to run consistency check sagas periodically.
Fun.CQRS does not support it for the moment. We do have a ConsistencyChecker in one of our projects that we will integrate in Fun.CQRS soon. 

Note that this situation is related to the nature of akka-persistence. We can't say to akka-persistence: persist the event and execute this other action in one single transaction. Akka persistence does not have the notion of transaction. 

This could be perfectly doable if we had a SlickBackend for instance. Than we could have something like:


```scala
object LotteryCreationService {
   def reserve(id: LotteryId, name: String): DBIO[Unit] = {
     // here some logic to check if the name is already in use or not
     // if not in use, add it to table and return DBIO.success 
     // if in use, DBIO.failure
   }
}
def createLottery(lotteryId: LotteryId) = 
    actions[Lottery]
      .handleCommandInTransaction {
        cmd: CreateLottery => LotteryNameReservationService.reserve(lotteryId, cmd.name).map { _ =>
           LotteryCreated(cmd.name, metadata(lotteryId, cmd))
        }
      }
     ...
```

The DBIO could then be executed in one single transaction. If the name is already in user, then the event is not persisted and the command is rejected. 
If the name is not in use, we reserve it on the same transaction we save the event.

**Comment by rcavalcanti** [comment]
Hi @CrowdHailer,

I'm closing this 'question'. Please reopen it if you want to discuss it further or if you think the answer is not satisfatory.
