### ISSUE TITLE
ViewBoundedAggregateActorRef is never used

### ISSUE THREAD

**Issue by pocman** [strongtyped/fun-cqrs#58]
Hi,

I'm trying to understand all the work behind the `AkkaBackend` and I'm stuck trying to figure out how `ViewBoundedAggregateActorRef` can be used.
Could you provide some example on this topic ?

Thanks !

**Comment by rcavalcanti** [comment]
Hi @pocman, my excuses for the late reply. I was on vacation when you send your message.

The `ViewBoundedAggregateActorRef` is a hidden feature that I'm not so happy with, that's the reason why it's not documented (it may disappear one day).

So, how it works? 
Basically, the idea is to bound an aggregate to a view projection. This is only available for `AggregateActorRef`.

You can get one by calling the `AggregateActorRef.join`. 

When you send a command to an AggregateRef using the ask method (?), you get back a Future[Seq[Event]]. If you send a command to one that is bounded to a view, the returned Future only completes when the events have been processed by the view you choose to join.

Note that this is a very tricky feature and totally not aligned with the CQRS principles. That's why I'm keeping it hidden.
