### ISSUE TITLE
Upgrade EventsSourceProvider to use akka.persistence.query.EventEnvelope2 in Akka 2.4

### ISSUE THREAD

**Issue by aiacovella** [strongtyped/fun-cqrs#72]
It is currently using EventEnvelope with an offset of type Long whereas in the latest Akka libs, that was deprecated in favor of EventEnvelope2 with an offset of type Offset

**Comment by lmlynik** [comment]
In akka 2.5 it will be renamed back to EventEnvelope so it will be fixed when that will be released

**Comment by rcavalcanti** [comment]
Yes, but the type won't be compatible. 

Current `EventEnvelope` only supports `Long`. 

`EventEnvelope` has an `Offset` instead which can be a Long or a timebase UUID.

So, we need to move to `EventEnvelope2` and support both Long and UUID. I've been working on that this recently and for the moment I will concentrate on getting this PR #77 merged.

After that, I need to re-think the projections in other to support both types of `Offset`.

**Comment by rcavalcanti** [comment]
This is done on the last milestone release (v1.0.0-M2). 

The new projection design is agnostic of `EventEnvelope` because it's not linked to backend anymore. You can create any projection based on whatever stream technology as long as you have a integration point with `org.reactivestreams.Publisher`.
