### ISSUE TITLE
RxScala dependency for 2.11

### ISSUE THREAD

**Issue by datalchemist** [strongtyped/fun-cqrs#80]
Hi,
Versions 0.4.9 and 0.4.10 depends on RxScala 2.12. I can see that it is actually hard-coded in your dependency files: "rxscala_2.12"

It looks like a problem. Is there a reason for this?

Best

**Comment by rcavalcanti** [comment]
Yes, the reason is that they are not providing a version for 2.11 for their latest version.
And they are not providing a 2.12 for their previous version. 

I have to hard coded it because we are now supporting cross build (2.11 and 2.12) and I need a version that works for both builds. 

However, you force me to review it and I just realised that it's being added as a dependency on fun-cqrs-core. This is wrong, rxscala is only used by fun-cqrs-test-kit. 

I will leave this issue open to fix later.

thanks

**Comment by datalchemist** [comment]
Ok, I see.
Note that it seems that the rxScala version you use, 0.26.4, is (at least now) actually available for both 2.11 and 2.12 So, I guess it should not be necessary anymore to stick to the 2.12 version.

Concerning the dependency on fun-cqrs-core, RxScala is indeed referenced in the "mainDeps" which are used for all projects AND it is also referenced individually in the testkit project. So, I guess it should simply be removed from "mainDeps".

So, for the moment, I will stick to version 0.4.8 to avoid rxScala 2.12.

Thank you

**Comment by rcavalcanti** [comment]
Feel free to send a PR if you want. I can make a quick release for you.

**Comment by datalchemist** [comment]
Yes, I can do that. That sounds good.
However, I don't have the rights to push my changes. Could you add me to the contributors?

**Comment by rcavalcanti** [comment]
the way to do is to fork the repo, push the changes to your fork and open a PR

**Comment by rcavalcanti** [comment]
When you push to your fork, GitHub will ask if you want to send a PR to the original Repo. That's how you start the process.

**Comment by datalchemist** [comment]
Ok, sorry, I am quite new with github contributions...

Anyway, I did like you said and submitted a PR on the master branch.
